---
title: "BDA - Project report"
author: "Anonymous"
output: 
  pdf_document: 
    toc: yes
    toc_depth: 3
urlcolor: blue
---

```{r, include=FALSE}
library(rstan)
library(ggplot2)
library(posterior)
library(loo)
library(patchwork)
library(dplyr)
```

First, let us import the data into its own dataframe:

```{r}
burnout <- read.csv('data/burnout.csv')
head(burnout)
```
```{r}
ggplot() + 
  geom_point(data=burnout, aes(x=fatigue_score, y=burn_rate, col=sex, alpha=0.5))
```


Let's do a bit of data analysis:

```{r, fig.width=14, fig.height=5}
df_plot <- as.data.frame(table(burnout$sex))
df_plot$Freq <- df_plot$Freq / sum(df_plot$Freq)

sex_percent <- ggplot(data=df_plot, aes(x="", y=Freq, fill=Var1))+
  geom_bar(stat='identity', width=0.5) + 
  labs(title='Percentage of Female vs Male') + 
  guides(fill=guide_legend(title='Sex')) + 
  scale_y_continuous(labels = scales::percent) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank())

df_plot <- as.data.frame(table(burnout$company_type))
df_plot$Freq <- df_plot$Freq / sum(df_plot$Freq)

company_percent <- ggplot(data=df_plot, aes(x="", y=Freq, fill=Var1))+
  geom_bar(stat='identity', width=0.5) + 
  labs(title='Percentage of Product vs Service company') +
  guides(fill=guide_legend(title='Company type')) + 
  scale_y_continuous(labels = scales::percent) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank())

df_plot <- as.data.frame(table(burnout$wfh))
df_plot$Freq <- df_plot$Freq / sum(df_plot$Freq)

wfh_percent <- ggplot(data=df_plot, aes(x="", y=Freq, fill=Var1))+
  geom_bar(stat='identity', width=0.5) + 
  labs(title='Percentage of Cannot work remotely vs Can work remotely') +
  guides(fill=guide_legend(title='Work from home set up')) + 
  scale_y_continuous(labels = scales::percent) +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank())


sex_percent + company_percent + wfh_percent
```


